// <auto-generated />
namespace VexTeamNetwork.Migrations.CoreContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixEventVenueAndContact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixEventVenueAndContact));
        
        string IMigrationMetadata.Id
        {
            get { return "201507281919202_FixEventVenueAndContact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
